apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-loan-txn-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-loan-txn-job
  template:
    metadata:
      labels:
        app: flink-loan-txn-job
    spec:
      containers:
        - name: flink-loan-txn-job-container
          image: 376163012258.dkr.ecr.us-east-1.amazonaws.com/flink-loan-txn-app:latest